# Generated by Django 4.2.2 on 2023-06-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tagged_pets',
        ),
        migrations.AddField(
            model_name='photo',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, null=True, to='pets.pet'),
        ),
    ]
