# Generated by Django 4.2.2 on 2023-06-20 15:38

import django.core.validators
from django.db import migrations, models
import plants.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], validators=[django.core.validators.MaxLengthValidator(14)])),
                ('name', models.CharField(validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(2), plants.validators.name_validator])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
