# Generated by Django 4.2.1 on 2023-06-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.URLField(default='https://cdn.jpegmini.com/user/images/slider_puffin_before_mobile.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(default='Artist', max_length=30),
            preserve_default=False,
        ),
    ]
