# Generated by Django 4.2.2 on 2023-06-20 16:27

import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(validators=[django.core.validators.MaxLengthValidator(20), profiles.validators.name_validator])),
                ('last_name', models.CharField(validators=[django.core.validators.MaxLengthValidator(20), profiles.validators.name_validator])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
